#!/usr/bin/env python3
"""Generates the v1.8 widget face layouts (CCRM-78 (Widgets Reborn)).

Each face gets three files -- base, _sd and _sl -- that differ only in the text style,
because RemoteViews cannot set a text shadow at runtime and a Transparent face needs
one in the opposite tone (wireframe rev D). Edit this script, never the XML, then run
    python3 tools/widget_layouts.py
WidgetLayoutsTest fails if the three drift.
"""
import os
RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'app', 'src', 'main', 'res')
A='xmlns:android="http://schemas.android.com/apk/res/android"'

def tv(id, size, extra='', w='wrap_content', h='wrap_content', vis='gone', bold=False, text=None):
    b = '\n        android:textStyle="bold"' if bold else ''
    t = f'\n        android:text="{text}"' if text else ''
    v = f'\n        android:visibility="{vis}"' if vis else ''
    return f'''<TextView
        android:id="@+id/{id}"
        style="@style/STYLE"
        android:layout_width="{w}"
        android:layout_height="{h}"
        android:textSize="{size}sp"{b}{t}{v}{extra} />'''

def img(id, w, h, extra='', vis=None, src=None):
    v = f'\n        android:visibility="{vis}"' if vis else ''
    s = f'\n        android:src="@drawable/{src}"' if src else ''
    return f'''<ImageView
        android:id="@+id/{id}"
        android:layout_width="{w}"
        android:layout_height="{h}"
        android:importantForAccessibility="no"{s}{v}{extra} />'''

def frame(comment, content):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!--
{comment}

    GENERATED by tools/widget_layouts.py — the three files of this face (base, _sd, _sl) differ only in the text
    style: WFace, WFace.ShadowDark or WFace.ShadowLight (a Transparent face's soft shadow
    in the opposite tone, rev D). WidgetLayoutsTest fails if they drift. Only views
    RemoteViews allows appear here; spacers are empty FrameLayouts, never <View>.
-->
<FrameLayout {A}
    android:id="@+id/w_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    {img('w_bg','match_parent','match_parent', chr(10)+'        android:scaleType="fitXY"', src='widget_bg')}

    {img('w_wash','match_parent','match_parent', chr(10)+'        android:scaleType="fitXY"', vis='gone', src='widget_wash')}

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <TextView
            android:id="@+id/w_ribbon"
            android:layout_width="match_parent"
            android:layout_height="12dp"
            android:background="#FF7C4DFF"
            android:gravity="center"
            android:letterSpacing="0.06"
            android:text="● SYNTHETIC"
            android:textColor="#FFFFFFFF"
            android:textSize="6.5sp"
            android:textStyle="bold"
            android:visibility="gone" />

        <FrameLayout
            android:id="@+id/w_pad"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1">

{content}

            {tv('w_msg','11.5', chr(10)+'        android:gravity="center"', w='match_parent', h='match_parent')}
        </FrameLayout>
    </LinearLayout>

    {img('w_synth_dot','7dp','7dp', chr(10)+'        android:layout_gravity="top|end"'+chr(10)+'        android:layout_margin="5dp"', vis='gone', src='widget_synth_dot')}
</FrameLayout>
'''

def ind(s, n):
    return '\n'.join((' '*n + l) if l.strip() else l for l in s.split('\n'))

def ll(id, orient, inner, w='match_parent', h='wrap_content', extra='', vis=None):
    i = f'\n    android:id="@+id/{id}"' if id else ''
    v = f'\n    android:visibility="{vis}"' if vis else ''
    return f'''<LinearLayout{i}
    android:layout_width="{w}"
    android:layout_height="{h}"
    android:orientation="{orient}"{v}{extra}>
{ind(inner,4)}
</LinearLayout>'''

def spacer(id=None, orient='h', vis=None):
    i = f'\n    android:id="@+id/{id}"' if id else ''
    v = f'\n    android:visibility="{vis}"' if vis else ''
    if orient == 'h':
        return f'<FrameLayout{i}\n    android:layout_width="0dp"\n    android:layout_height="1dp"\n    android:layout_weight="1"{v} />'
    return f'<FrameLayout{i}\n    android:layout_width="1dp"\n    android:layout_height="0dp"\n    android:layout_weight="1"{v} />'

def fix(x):  # the tv/img helpers indent attributes by 8; normalise to 4 inside ll/ind
    return x.replace('\n        android:', '\n    android:').replace('\n        style=', '\n    style=')

T = lambda *a, **k: fix(tv(*a, **k))
I = lambda *a, **k: fix(img(*a, **k))
N = '\n'
G = lambda g: f'{N}    android:gravity="{g}"'

# ------------------------------------------------------------------ Ring
# Rev H (CCBG-44 (Widget Fill)): RemoteViews cannot switch a LinearLayout's orientation, so
# the Ring carries both arrangements as siblings and shows one — the column (1×1, 2×1 and the
# tall tier T) or the row (the wide tiers: 3×1 and up, 4×2 and up). Suffix '' is the column,
# '_h' the row; the code addresses both through one id set each.
def ring_box(sfx):
    return f"""<FrameLayout
    android:id="@+id/ring_box{sfx}"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
{ind(I('ring'+sfx,'64dp','64dp'),4)}
{ind(T('ring_fig'+sfx,'16', N+'    android:layout_gravity="center"'+N+'    android:includeFontPadding="false"', vis=None, bold=True),4)}
</FrameLayout>"""

def ring_comp(sfx, extra):
    # The companion ring (rev H, Q1): the same account's other window, its word in the bore.
    return f"""<FrameLayout
    android:id="@+id/ring_comp_box{sfx}"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:visibility="gone"{extra}>
{ind(I('ring_comp'+sfx,'64dp','64dp'),4)}
{ind(ll(None,'vertical', chr(10).join([T('ring_comp_fig'+sfx,'22', N+'    android:includeFontPadding="false"', vis=None, bold=True), T('ring_comp_tag'+sfx,'9', N+'    android:includeFontPadding="false"', vis=None, bold=True)]), w='wrap_content', extra=G('center_horizontal')+N+'    android:layout_gravity="center"'),4)}
</FrameLayout>"""

def ring_lines(sfx, gravity):
    return '\n'.join([
        ll('ring_label_row'+sfx, 'horizontal', '\n'.join([
            I('ring_mark'+sfx,'12dp','12dp', N+'    android:layout_marginEnd="4dp"'),
            T('ring_label'+sfx,'12', N+'    android:singleLine="true"'+N+'    android:ellipsize="end"', vis=None),
            I('ring_dot'+sfx,'6dp','6dp', N+'    android:layout_marginStart="4dp"', vis='gone', src='notif_condition_dot'),
        ]), w='wrap_content', extra=G('center_vertical'), vis='gone'),
        T('ring_reset'+sfx,'12', N+'    android:layout_marginTop="2dp"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"'),
        T('ring_stamp'+sfx,'10', N+'    android:layout_marginTop="2dp"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"'),
    ])

ring = f"""<FrameLayout
    android:id="@+id/ring_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
{ind(ll('ring_col', 'vertical', chr(10).join([
    ring_box(''),
    ll('ring_lines', 'vertical', ring_lines('', 'center_horizontal'), w='wrap_content', extra=G('center_horizontal')+N+'    android:layout_marginTop="6dp"', vis='gone'),
    ring_comp('', N+'    android:layout_marginTop="8dp"'),
]), h='match_parent', extra=G('center')), 4)}
{ind(ll('ring_row', 'horizontal', chr(10).join([
    ring_box('_h'),
    ll('ring_lines_h', 'vertical', ring_lines('_h', 'start'), w='0dp', extra=N+'    android:layout_weight="1"'+N+'    android:layout_marginStart="12dp"', vis='gone'),
    ring_comp('_h', N+'    android:layout_marginStart="8dp"'),
]), h='match_parent', extra=G('center_vertical'), vis='gone'), 4)}
</FrameLayout>"""
ring += '\n\n' + I('ring_corner_dot','6dp','6dp', N+'    android:layout_gravity="top|end"', vis='gone', src='notif_condition_dot')

# ------------------------------------------------------------------ Number
def chip(id):
    # The text is match_parent too: FrameLayout stretches match_parent children of a
    # wrap_content frame only when there are two or more, else the bg collapses to 1 px.
    return f'''<FrameLayout
    android:id="@+id/{id}"
    android:layout_width="wrap_content"
    android:layout_height="24dp"
    android:layout_marginEnd="6dp"
    android:visibility="gone">
{ind(I(id+'_bg','match_parent','match_parent', N+'    android:scaleType="fitXY"', src='widget_chip'),4)}
{ind(T(id+'_text','11', N+'    android:gravity="center"'+N+'    android:paddingStart="11dp"'+N+'    android:paddingEnd="11dp"', h='match_parent', vis=None),4)}
</FrameLayout>'''

number = ll('num_col', 'vertical', '\n'.join([
    ll('num_reading', 'vertical', '\n'.join([
        ll(None, 'horizontal', '\n'.join([
            ll(None, 'vertical', '\n'.join([
                T('num_pill','8', N+'    android:layout_marginStart="18dp"'+N+'    android:paddingStart="4dp"'+N+'    android:paddingEnd="4dp"'+N+'    android:background="@drawable/widget_pill"'+N+'    android:letterSpacing="0.05"', bold=True, text='UNASSIGNED'),
                ll(None, 'horizontal', '\n'.join([
                    I('num_mark','14dp','14dp', N+'    android:layout_marginEnd="4dp"'),
                    T('num_label','13', N+'    android:singleLine="true"'+N+'    android:ellipsize="end"', vis=None),
                    I('num_dot','6dp','6dp', N+'    android:layout_marginStart="4dp"', vis='gone', src='notif_condition_dot'),
                ]), extra=G('center_vertical')),
                T('num_weekly2','10', N+'    android:layout_marginStart="18dp"', bold=True, text='Weekly'),
            ]), w='0dp', extra=N+'    android:layout_weight="1"'+N+'    android:paddingBottom="3dp"'),
            T('num_fig','32', N+'    android:layout_marginStart="10dp"'+N+'    android:includeFontPadding="false"'+N+'    android:singleLine="true"', vis=None, bold=True),
            T('num_leftcap','10', N+'    android:layout_marginStart="4dp"'+N+'    android:letterSpacing="0.08"', bold=True, text='LEFT'),
        ]), extra=G('bottom')),
        # rev F (CCBG-38 (Cover Buckets)): a 2×1 frame too narrow for label and figure on one
        # row shows the figure here, under the label, instead of beside it.
        T('num_fig_below','32', N+'    android:layout_marginTop="2dp"'+N+'    android:includeFontPadding="false"'+N+'    android:singleLine="true"', bold=True),
        I('num_bar','match_parent','12dp', N+'    android:layout_marginTop="1dp"'+N+'    android:scaleType="fitXY"'),
        ll('num_subrow', 'horizontal', '\n'.join([
            T('num_sub','12', N+'    android:includeFontPadding="false"'+N+'    android:layout_weight="1"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"', w='0dp', vis=None),
            T('num_stamp','10', N+'    android:includeFontPadding="false"'+N+'    android:layout_marginStart="8dp"'+N+'    android:singleLine="true"'),
        ]), extra=G('bottom')+N+'    android:layout_marginTop="2dp"', vis='gone'),
        # rev H: the Number 2×2 (tall tier, CCBG-44 (Widget Fill)) puts the stamp on its own line.
        T('num_stamp_below','10', N+'    android:includeFontPadding="false"'+N+'    android:layout_marginTop="2dp"'+N+'    android:singleLine="true"'),
    ]), h='0dp', extra=N+'    android:layout_weight="1"'+G('center_vertical')),
    ll('num_ctrl', 'vertical', '\n'.join([ll('num_ctrl_row', 'horizontal', '\n'.join([
        chip('num_chip_s'), chip('num_chip_w'), chip('num_chip_fixed'),
        spacer(),
        f'''<FrameLayout
    android:id="@+id/num_cycler"
    android:layout_width="wrap_content"
    android:layout_height="24dp">
{ind(I('num_cycler_bg','match_parent','match_parent', N+'    android:scaleType="fitXY"', src='widget_chip'),4)}
{ind(ll(None,'horizontal', chr(10).join([I('num_cycler_mark','12dp','12dp', N+'    android:layout_marginEnd="5dp"'), T('num_cycler_text','11', N+'    android:singleLine="true"', vis=None, bold=True)]), w='wrap_content', h='match_parent', extra=G('center_vertical')+N+'    android:paddingStart="10dp"'+N+'    android:paddingEnd="10dp"'),4)}
</FrameLayout>''',
    ]), h='28dp', extra=G('center_vertical')),
    # rev H: on the Number 2×2 the cycler takes a row of its own under the chips.
    f'''<FrameLayout
    android:id="@+id/num_cycler2"
    android:layout_width="wrap_content"
    android:layout_height="24dp"
    android:layout_marginTop="4dp"
    android:visibility="gone">
{ind(I('num_cycler2_bg','match_parent','match_parent', N+'    android:scaleType="fitXY"', src='widget_chip'),4)}
{ind(ll(None,'horizontal', chr(10).join([I('num_cycler2_mark','12dp','12dp', N+'    android:layout_marginEnd="5dp"'), T('num_cycler2_text','11', N+'    android:singleLine="true"', vis=None, bold=True)]), w='wrap_content', h='match_parent', extra=G('center_vertical')+N+'    android:paddingStart="10dp"'+N+'    android:paddingEnd="10dp"'),4)}
</FrameLayout>''',
    ]), vis='gone'),
]), h='match_parent')

# ------------------------------------------------------------------ Countdown
countdown = ll('cd_col', 'vertical', '\n'.join([
    T('cd_caption','11', N+'    android:singleLine="true"', vis=None),
    ll('cd_countrow', 'horizontal', '\n'.join([
        f'''<Chronometer
    android:id="@+id/cd_chrono"
    style="@style/STYLE"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:includeFontPadding="false"
    android:singleLine="true"
    android:textSize="24sp"
    android:textStyle="bold"
    android:fontFeatureSettings="tnum"
    android:visibility="gone" />''',
        T('cd_abs','24', N+'    android:includeFontPadding="false"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"', bold=True),
        T('cd_at_inline','11', N+'    android:layout_marginStart="6dp"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"'),
        # rev H (CCBG-44 (Widget Fill)): a wide 1-row Countdown (5×1 and up) adds the figure
        # over a bar at the row's end, bottom-aligned to the count.
        spacer('cd_side_gap', vis='gone'),
        ll('cd_side', 'vertical', '\n'.join([
            ll(None, 'horizontal', '\n'.join([
                T('cd_side_fig','24', N+'    android:includeFontPadding="false"', vis=None, bold=True),
                T('cd_side_left','9', N+'    android:layout_marginStart="4dp"'+N+'    android:letterSpacing="0.08"', bold=True, text='LEFT'),
            ]), w='wrap_content', extra=G('bottom')),
            I('cd_side_bar','match_parent','8dp', N+'    android:layout_marginTop="3dp"'+N+'    android:scaleType="fitXY"'),
        ]), w='wrap_content', extra=N+'    android:layout_gravity="bottom"', vis='gone'),
    ]), extra=N+'    android:baselineAligned="true"'+N+'    android:layout_marginTop="2dp"'),
    T('cd_at_below','12', N+'    android:layout_marginTop="3dp"'+N+'    android:singleLine="true"'),
    T('cd_msg','13.5', N+'    android:includeFontPadding="false"', bold=True),
    spacer('cd_gap1', 'v', vis='gone'),
    ll('cd_figrow', 'horizontal', '\n'.join([
        T('cd_fig','18', N+'    android:includeFontPadding="false"', vis=None, bold=True),
        T('cd_leftcap','8.5', N+'    android:layout_marginStart="4dp"'+N+'    android:letterSpacing="0.08"', bold=True, text='LEFT'),
        spacer(),
        T('cd_est','11', N+'    android:singleLine="true"'),
    ]), extra=G('bottom'), vis='gone'),
    # rev F.1: the estimate's own line when it does not fit beside the figure.
    T('cd_est_below','11', N+'    android:layout_marginTop="2dp"'+N+'    android:singleLine="true"'),
    I('cd_bar','match_parent','10dp', N+'    android:layout_marginTop="2dp"'+N+'    android:scaleType="fitXY"', vis='gone'),
    spacer('cd_gap2', 'v', vis='gone'),
    # rev F: the account line gives way to the stamp. The weighted wrap_content group takes
    # any spare width at its end (the dot stays beside the label) and, when the row
    # overflows, shrinks — and its own weighted label ellipsizes — so the stamp stays whole.
    ll('cd_bottom', 'horizontal', '\n'.join([
        ll(None, 'horizontal', '\n'.join([
            I('cd_mark','11dp','11dp', N+'    android:layout_marginEnd="4dp"'),
            T('cd_label','11', N+'    android:layout_weight="1"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"', vis=None),
            I('cd_dot','6dp','6dp', N+'    android:layout_marginStart="4dp"', vis='gone', src='notif_condition_dot'),
        ]), w='wrap_content', extra=N+'    android:layout_weight="1"'+G('center_vertical')),
        T('cd_stamp','10', N+'    android:layout_marginStart="6dp"'+N+'    android:singleLine="true"'),
    ]), extra=G('center_vertical')+N+'    android:layout_marginTop="4dp"'),
]), h='match_parent', extra=G('center_vertical'))

# ------------------------------------------------------------------ Strip
def cell(i):
    return ll(f'strip_cell{i}', 'vertical', '\n'.join([
        f'''<FrameLayout
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
{ind(I(f'strip_ring{i}','53dp','53dp'),4)}
{ind(ll(None,'vertical', chr(10).join([T(f'strip_fig{i}','13', N+'    android:includeFontPadding="false"', vis=None, bold=True), T(f'strip_tag{i}','8', N+'    android:includeFontPadding="false"', bold=True, text='Weekly')]), w='wrap_content', extra=G('center_horizontal')+N+'    android:layout_gravity="center"'),4)}
{ind(T(f'strip_xtag{i}','8', N+'    android:layout_gravity="center"'+N+'    android:includeFontPadding="false"', bold=True, text='Weekly'),4)}
{ind(T(f'strip_free{i}','13', N+'    android:layout_gravity="center"'+N+'    android:includeFontPadding="false"', text='Free'),4)}
</FrameLayout>''',
        ll(None, 'horizontal', '\n'.join([
            I(f'strip_mark{i}','10dp','10dp', N+'    android:layout_marginEnd="3dp"'),
            T(f'strip_label{i}','9.5', N+'    android:includeFontPadding="false"'+N+'    android:singleLine="true"'+N+'    android:ellipsize="end"', vis=None),
            I(f'strip_dot{i}','5dp','5dp', N+'    android:layout_marginStart="3dp"', vis='gone', src='notif_condition_dot'),
        ]), w='wrap_content', extra=G('center_vertical')+N+'    android:layout_marginTop="3dp"'),
        T(f'strip_reset{i}','10', N+'    android:singleLine="true"'),
    ]), w='wrap_content', extra=G('center_horizontal'))

# rev H: the row is a centred group, and the stamp sits right under it, at its end.
strip = ll('strip_col', 'vertical', ll('strip_group', 'vertical', '\n'.join([
    ll('strip_row', 'horizontal', '\n'.join([cell(i) for i in range(4)] + [
        T('strip_plus','13', N+'    android:layout_marginStart="6dp"', bold=True)]), w='wrap_content', extra=G('center_vertical')),
    T('strip_stamp','10', N+'    android:layout_gravity="end"'+N+'    android:layout_marginTop="6dp"'+N+'    android:singleLine="true"'),
]), w='wrap_content'), h='match_parent', extra=G('center'))

faces = {
  'widget_ring': ('    CCRM-79 (Ring Face): the rails ring (a RingRenderer TICK bitmap) with the figure in\n    its bore as real text; on 2×2 a label line under it.', ring),
  'widget_number': ('    CCRM-80 (Number Face): label and figure on one row, the bar under both, the absolute\n    sub-line from 4×1, and the 4×2 control row (window chips, account cycler).', number),
  'widget_countdown': ('    CCRM-81 (Countdown Face): caption, the live chronometer or an absolute time, and on\n    2×2 the figure row over a 6 dp bar; the account line at the bottom.', countdown),
  'widget_strip': ('    CCRM-82 (Accounts Strip): up to four rings, each its own account in its own accent,\n    and a "+N" cell. Never a sum.', strip),
}
for name, (comment, content) in faces.items():
    base = frame(comment, ind(content, 12))
    for suffix, style in [('', 'WFace'), ('_sd', 'WFace.ShadowDark'), ('_sl', 'WFace.ShadowLight')]:
        open(f'{RES}/layout/{name}{suffix}.xml', 'w').write(base.replace('@style/STYLE', f'@style/{style}'))
print('ok')
